### ISSUE TITLE
ticket list pagination is missing at customer panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#122]
**Description**  
![Screenshot_302](https://user-images.githubusercontent.com/43210406/108671819-0a1fa900-7507-11eb-9895-735ad8748cfa.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

The issue has been fixed in master branch [here ](https://github.com/uvdesk/support-center-bundle/commit/226cc0a1318ceea4e7b121386845f3f89615e151) and reflect from upcoming release of project.

Till then you can avail it by doing below steps:

Locate path in your project:
**vendor/uvdesk/support-center-bundle**

Remove **support-center-bundle** from here and download or clone **support-center-bundle** form [here](https://github.com/uvdesk/support-center-bundle).

Place new **support-center-bundle** under **vendor/uvdesk** folder.

Finally run a command:
**php bin/console assets:install**

Clear project cache by:
**php bin/console c:c**

Now you will get paging in customer panel.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
fixed now https://prnt.sc/1068pjz
